[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd website && npm ci"]

[phases.build]
cmds = ["cd website && npm run build"]

[start]
cmd = "cd website && node build"
